name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "The New Release"
        required: true

env:
  RELEASE: ${{ github.event.inputs.release }}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: "1.17.3"

      - name: Release
        run: |
          gh auth login --with-token ${{ secrets.TOKEN }}
          sudo chmod 755 ./release.sh
          ./release.sh ${{ env.RELEASE }}
